#!/usr/bin/perl -w
use Qt 2.0;
import Qt::app;

$box = Qt::VBox->new;
$box->resize(200, 120);

$quit = Qt::PushButton->new('Quit', $box);
$quit->setFont(Qt::Font->new('Times', 18, Qt::Font::Bold));

$app->connect($quit, 'clicked()', 'quit()');

$app->setMainWidget($box);
$box->show();
exit $app->exec();
