#!/usr/bin/perl -w
use Qt 2.0;
import Qt::app;

$w = Qt::Widget->new;
$w->resize(200, 120);

$quit = Qt::PushButton->new('Quit', $w);
$quit->move(62, 40);
$quit->resize(75, 30);
$quit->setFont(Qt::Font->new('Times', 18, Qt::Font::Bold));

$app->connect($quit, 'clicked()', 'quit()');

$app->setMainWidget($w);
$w->show();
exit $app->exec();
