#!/usr/bin/perl -w
package MyWidget;

use Qt qw($app %Weight);

use CannonField;
use LCDRange;

@ISA = qw(QWidget);

sub new {
    my $self = shift->SUPER::new(@_);

    $self->setMinimumSize(500, 355);

    my $quit = QPushButton->new('Quit', $self, 'quit');
    $quit->setGeometry(10, 10, 75, 30);
    $quit->setFont(QFont->new('Times', 18, $Weight{Bold}));
    $app->connect($quit, 'clicked()', 'quit()');

    my $angle = LCDRange->new($self, 'angle');
    $angle->setRange(5, 70);
    $angle->setGeometry(10, $quit->y() + $quit->height() + 10, 75, 130);

    my $cannonField = CannonField->new($self, 'cannonField');
    $cannonField->move($angle->x() + $angle->width() + 10, $angle->y());
    $cannonField->setBackgroundColor(QColor->new(250, 250, 200));

    $cannonField->connect($angle, 'valueChanged(int)', 'setAngle(int)');
    $angle->connect($cannonField, 'angleChanged(int)', 'setValue(int)');

    $angle->setValue(60);

    @$self{'quit', 'angle', 'cannonField'} = ($quit, $angle, $cannonField);
    return $self;
}

sub resizeEvent {
    my $self = shift;
    my $cannonField = $self->{'cannonField'};

    $cannonField->resize($self->width()  - $cannonField->x() - 10,
			 $self->height() - $cannonField->y() - 10);
}

package main;

use Qt 2.0;

$w = MyWidget->new;
$w->setGeometry(100, 100, 500, 355);
$app->setMainWidget($w);
$w->show();
exit $app->exec();
