#!/usr/bin/perl -w
use Qt qw($app %Weight);

$w = QWidget->new;
$w->resize(200, 120);

$quit = QPushButton->new('Quit', $w);
$quit->move(62, 40);
$quit->resize(75, 30);
$quit->setFont(QFont->new('Times', 18, $Weight{Bold}));

$app->connect($quit, 'clicked()', 'quit()');

$app->setMainWidget($w);
$w->show();
exit $app->exec();
