#!/usr/bin/perl -w
use Qt 2.0;
#BEGIN { Qt::Application::setColorSpec(Qt::Application::CustomColor) }
use GameBoard;
import Qt::app;

$gb = GameBoard->new;
$app->setMainWidget($gb);
$gb->show();
exit $app->exec();
