#!/usr/bin/perl -w
package MyWidget;

use Qt qw($app %Weight);

@ISA = qw(QWidget);

sub new {
    my $self = shift->SUPER::new(@_);

    $self->setMinimumSize(200, 120);
    $self->setMaximumSize(200, 120);

    my $quit = QPushButton->new('Quit', $self, 'quit');
    $quit->setGeometry(62, 40, 75, 30);
    $quit->setFont(QFont->new('Times', 18, $Weight{Bold}));

    $app->connect($quit, 'clicked()', 'quit()');

    return $self;
}

package main;

use Qt 2.0;

$w = MyWidget->new;
$w->setGeometry(100, 100, 200, 120);
$app->setMainWidget($w);
$w->show();
exit $app->exec();
