#!/usr/bin/perl -w
package MyWidget;

use Qt 2.0;
import Qt::app;

use CannonField;
use LCDRange;

@ISA = qw(Qt::Widget);

sub new {
    my $self = shift->SUPER::new(@_);

    $self->setMinimumSize(500, 355);

    my $quit = Qt::PushButton->new('Quit', $self, 'quit');
    $quit->setFont(Qt::Font->new('Times', 18, Qt::Font::Bold));
    $app->connect($quit, 'clicked()', 'quit()');

    my $angle = LCDRange->new($self, 'angle');
    $angle->setFixedHeight(70);
    $angle->setRange(5, 70);

    my $cannonField = CannonField->new($self, 'cannonField');

    $cannonField->connect($angle, 'valueChanged(int)', 'setAngle(int)');
    $angle->connect($cannonField, 'angleChanged(int)', 'setValue(int)');

    my $grid = Qt::GridLayout->new($self, 2, 2, 10);
    $grid->addWidget($quit, 0, 0);
    $grid->addWidget($angle, 1, 0, Qt::AlignTop);
    $grid->addWidget($cannonField, 1, 1);
    $grid->setColStretch(1, 10);

    $angle->setValue(60);

    return $self;
}

package main;

use Qt 2.0;
import Qt::app;

$w = MyWidget->new;
$w->setGeometry(100, 100, 500, 355);
$app->setMainWidget($w);
$w->show();
exit $app->exec();
