#!/usr/bin/perl -w
use Qt;
use Editor;

$e = new Editor->immortal;
$e->resize(400, 400);
$e->show();

for(@ARGV) {
    $e = new Editor->immortal;
    $e->resize(400, 400);
    $e->loadFile($_);
    $e->show();
}
$qApp->connect($qApp, 'lastWindowClosed()', 'quit()');
exit $qApp->exec();
