use ExtUtils::MakeMaker;

WriteMakefile(
    NAME	=> $::name,
    CC		=> 'g++',
    CCFLAGS	=> '-DHAS_BOOL',
    LIBS	=> '-lperlqt -lqt',
    OPTIMIZE	=> '-O2 -m486 -pipe',
    INC		=> '-I. -I../../include -I$(QTDIR)/include',
    PM		=> {},
    depend	=> { '$(C_FILES)' => '../typemap',
		     '$(FIRST_MAKEFILE)' => '../Makefile.Qt' },
    realclean	=> { FILES => 'Makefile.PL' },
);
