#!/usr/bin/perl
#
# convert_class QClass QNew
#
# eases the creation of largely duplicate virtual function class stubs
#

if(@ARGV < 2) { print "more args\n"; exit(-1); }

$old = $ARGV[0];
$new = $ARGV[1];
$ld = $old;
$ew = $new;
$ld =~ s/^.//;
$ew =~ s/^.//;

open(IN, "$old.c") || die "$old.xs: $!";
open(OUT, ">$new.c") || die "$new.xs: $!";

while(<IN>) {
    last if /virtualize/;
    s/Q$ld(\::)/Q$ew$1/g;
    print OUT $_;
}
