#!/usr/bin/perl -w
package MyWidget;

use Qt qw($app %Weight %Orientation);

@ISA = qw(QWidget);

sub new {
    my $self = shift->SUPER::new(@_);

    $self->setMinimumSize(200, 200);

    my $quit = QPushButton->new('Quit', $self, 'quit');
    $quit->setGeometry(10, 10, 75, 30);
    $quit->setFont(QFont->new('Times', 18, $Weight{Bold}));

    $app->connect($quit, 'clicked()', 'quit()');

    my $lcd = QLCDNumber->new(2, $self, 'lcd');
    $lcd->move(10, $quit->y() + $quit->height() + 10);

    my $sBar =
	QScrollBar->new(0, 99,				# range
		        1, 10,				# line/page steps
		        0,				# initial value
		        $Orientation{Horizontal},	# orientation
		        $self, 'scrollbar');

    $lcd->connect($sBar, 'valueChanged(int)', 'display(int)');

    @$self{'sBar', 'lcd'} = ($sBar, $lcd);
    return $self;
}

sub resizeEvent {
    my $self = shift;
    my($sBar, $lcd) = @$self{'sBar', 'lcd'};

    $sBar->setGeometry(10, $self->height() - 10 - 16, $self->width() - 20, 16);
    $lcd->resize($sBar->width(), $sBar->y() - $lcd->y() - 5);
}

package main;

use Qt;

$w = MyWidget->new;
$w->setGeometry(100, 100, 200, 200);
$app->setMainWidget($w);
$w->show();
exit $app->exec();
